-- 2. Definir usando listas por comprensión las funciones:
-- a) cambios :: [a] -> [Int], que dada una lista, devuelve la lista de los índices en que la lista cambia.
-- Es decir, dada la lista S retorna la lista con los i tal que Si /= S(i+1)
-- cambios [1,1,1,3,3,1,1] = [2,4]